-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 20:50:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gorozeroium_dh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gorozeroium_dh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gorozeroium_dh` DEFAULT CHARACTER SET utf8 ;
USE `gorozeroium_dh` ;

-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`user` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `genre` VARCHAR(20) NULL,
  `cpf` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `is_admin` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`category` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`product_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`product_type` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`product_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_type_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_type_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `gorozeroium_dh`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`product` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `type` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  `description` VARCHAR(1000) NULL,
  `rating` TINYINT(1) NULL,
  `abv` DECIMAL(10,2) NULL,
  `ibu` DECIMAL(10,2) NULL,
  `type_glass` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_product_type1_idx` (`product_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_product_type1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `gorozeroium_dh`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`user_address` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`user_address` (
  `user_id` INT NOT NULL,
  `cep` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  INDEX `fk_user_address_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gorozeroium_dh`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`cart` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `total` DECIMAL(10,2) NULL,
  `status` BIT(1) NULL,
  `shipment_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gorozeroium_dh`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`request` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `cart_id` INT NOT NULL,
  `status` BIT(1) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `shipment_date` DATE NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_request_cart1_idx` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gorozeroium_dh`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `gorozeroium_dh`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`cart_item` (
  `id` INT NOT NULL,
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_cart_item_cart1_idx` (`cart_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_item_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_item_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `gorozeroium_dh`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `gorozeroium_dh`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`request_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`request_item` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`request_item` (
  `id` INT NOT NULL,
  `request_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_item_request1_idx` (`request_id` ASC) VISIBLE,
  INDEX `fk_request_item_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_item_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `gorozeroium_dh`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `gorozeroium_dh`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorozeroium_dh`.`product_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorozeroium_dh`.`product_reviews` ;

CREATE TABLE IF NOT EXISTS `gorozeroium_dh`.`product_reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rating` TINYINT(1) NOT NULL,
  `comment` VARCHAR(300) NOT NULL,
  `comment_rating` INT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_reviews_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_reviews_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `gorozeroium_dh`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
